Optimizations and added text to speech
Zracano/Gesture-Recognition pull request #8
Opened 2022-11-15 20:06 UTC by Amark18

Cleaned up code, made some optimizations, fixed some issues, and added text to speech. I also made pattern recognition modular and is now called from gesture_detection_main.py so that gesture_detected.py can do the same as they both require that image/frame.

2022-11-15 20:32 UTC, Zracano requested changes
check the comment in gesture_detection_main.py

2022-11-15 20:32 UTC, Zracano commented on gesture_detection_main.py
>  if __name__ == '__main__':
If possible can we make a main() function that is called? I think that is a standard practice rather than code running in the if block.

2022-11-16 00:42 UTC, Amark18 commented
Added main() in if block, along with some optimizations.

2022-11-16 00:46 UTC, Zracano approved these changes
Great!

2022-11-16 00:46 UTC, merged